apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
    {{- include "fullstack.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
  selector:
    {{- include "fullstack.frontend.selectorLabels" . | nindent 4 }}
