apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fullstack.labels" . | nindent 4 }}
    {{- include "fullstack.backend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
  selector:
    {{- include "fullstack.backend.selectorLabels" . | nindent 4 }}
